import Link from "next/link";
import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { event } from "@/lib/event";
export const metadata: Metadata = { title: "Thank you | AI Made Easy Summit", description: "Next steps for AI Made Easy Summit ticket holders.", robots: { index: false, follow: false } };
export default function ThankYouPage() {
return <><Header /><main id="main"><section className="thankyou-hero"><div className="summit-wrap"><p className="eyebrow">AI Made Easy Summit</p><h1 className="metal">The next step?<br /><em>Make it practical.</em></h1><p className="thanks-lede">Thank you for being part of AI Made Easy.</p><p className="thanks-detail">Your successful payment receipt is your ticket confirmation.</p><div className="hero-facts"><span>{event.location}</span><span>Friday · {event.date}</span></div><p className="small-note">If you haven’t completed payment, your booking is not yet confirmed.</p></div></section><section className="summit-section"><div className="summit-wrap"><p className="eyebrow">Before we see you</p><h2 className="metal">Three simple <em>next steps.</em></h2><div className="focus-grid"><article><span className="section-number">01</span><h3>Keep your receipt</h3><p>Check the email address you used at checkout for your payment receipt and booking details.</p><p>Check promotions or spam if they haven’t appeared.</p></article><article><span className="section-number">02</span><h3>Keep 18 June free</h3><p>The main event is Friday 18 June 2027 in Surfers Paradise on the Gold Coast.</p><p>Venue and session times will be shared once confirmed.</p></article><article><span className="section-number">03</span><h3>Bring a real challenge</h3><p>Think of one marketing or business task that takes more time than it should.</p><p>Use it as your focus for the day.</p></article></div><div className="thanks-back"><p>Know someone who belongs in this room?</p><Link className="summit-btn" href="/">View the event page ↗</Link></div></div></section></main><Footer /></>;
}
